### ISSUE TITLE
严重错误：服务端接收信息出错

### ISSUE THREAD

**Issue by bigGiant** [NWAFU/dms_server#34]
- 接收到的日志信息出现乱码
- 接收到的日志数量错误

**Comment by Fibird** [comment]
在本地测试目前没有出现这样的问题，我现在能想到的原因有一下几个：

- 编码问题：两台主机一个是中文，一个是英文，使用的编码方式不同；
- 代码兼容性问题：测试时，两台电脑位数并不相同，客户端（发送方）为64bit，服务端（接收端）为32bit；
- 代码不够鲁棒：极其隐蔽的编码问题导致这样的运行时错误；

目前仍在解决中...

**Comment by bigGiant** [comment]
很痛苦，LCY问题严重

**Comment by Fibird** [comment]
参考https://stackoverflow.com/questions/2862071/how-large-should-my-recv-buffer-be-when-calling-recv-in-the-socket-library

**Comment by bigGiant** [comment]
wow, cool

**Comment by Fibird** [comment]
经过几天的奋战，终于找到了解决方案：

- 客户端
        - 客户端降低发送速度
- 服务端
        - 如收到的数据小于预期长度，则多次接收
        - 接收错误则抛出异常终止接收线程
